### ISSUE TITLE
Delete your idea

### ISSUE THREAD

**Issue by 17thFox** [mariuscoto/github-connect#22]

**Comment by mariuscoto** [comment]
Yes, we need this, and it would also be nice if we could limit the number of ideas a user can add each day to avoid spam. Also, use it for projects.

**Comment by mariuscoto** [comment]
do you need some guidelines for this task ?

**Comment by 17thFox** [comment]
Yes, i would happily accept them, it would help me a lot!

**Comment by mariuscoto** [comment]
These are the steps you should follow:
- Add a red, 'Delete idea' button in the 'Settings' panel of each idea and make it a link to '/idea-remove'. (all these must be done inside ideas.jade); if you may, add an alert that asks the user if he is sure he wants to delete it.
- Add a new route inside app.js, that catches requests from '/idea-remove' and handles them inside 'route/index.js' file
- Build handler in 'route/index.js' that: first checks if user is logged in, removes idea from database (watch exports.idea_add_fav as example, but use remove instead of update) and redirects to '/ideas'.

**Comment by mariuscoto** [comment]
Also, please make sure you delete all associated links in db: e.g. all comments for that idea. I can help you with that, after the steps from above are complete. :)

**Comment by 17thFox** [comment]
Thank you, i've sent you a pull request :octocat:

**Comment by mariuscoto** [comment]
The dialog box that makes sure I want to delete repo, does not work on my computer. Also, please move the button in line with to other one, but aligned to right.
